# Generated by Django 3.1.3 on 2021-01-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviated', models.CharField(max_length=100, verbose_name='Аббревиатура')),
                ('name', models.CharField(max_length=300, verbose_name='Полное название')),
                ('link', models.CharField(max_length=300, verbose_name='Ссылка на страницу ресурса')),
                ('logo', models.CharField(max_length=50, verbose_name='Герб университета')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
                'unique_together': {('abbreviated', 'name', 'link', 'logo')},
            },
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('date_opinion', models.CharField(max_length=40, verbose_name='Дата отзыва')),
                ('status', models.CharField(max_length=5, verbose_name='Статус')),
                ('status_ai', models.CharField(max_length=5, null=True, verbose_name='Статус ИИ')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_reviews.universities', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
