# Generated by Django 3.1.3 on 2021-01-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название университета')),
                ('link', models.TextField(verbose_name='Ссылка на его страницу')),
            ],
            options={
                'verbose_name': 'Рейтинги университета',
                'verbose_name_plural': 'Рейтинги университетов',
            },
        ),
    ]
