# Generated by Django 3.1.3 on 2021-01-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_reviews', '0002_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='rating_brand',
            field=models.IntegerField(null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='rating_education',
            field=models.IntegerField(null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='rating_innovation',
            field=models.IntegerField(null=True, verbose_name='Инновации'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='rating_internationalization',
            field=models.IntegerField(null=True, verbose_name='Интернационализация'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='rating_research',
            field=models.IntegerField(null=True, verbose_name='Исследования'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='rating_socialization',
            field=models.IntegerField(null=True, verbose_name='Социализация'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='rating_summary',
            field=models.IntegerField(null=True, verbose_name='Сводный рейтинг'),
        ),
    ]
