# Generated by Django 3.1.3 on 2021-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_reviews', '0003_auto_20210122_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='link',
            field=models.CharField(max_length=160, verbose_name='Ссылка на его страницу'),
        ),
    ]
